### ISSUE TITLE
Host Container and Application Wrapper sample code is invalid

### ISSUE THREAD

**Issue by concubicycle** [RickStrahl/Westwind.RazorHosting#11]
There are a few errors in the code snippet under "A better apporach -  Host Container and Application Wrapper". 

The error out parameter is missing type string. 
`host.AddAssemblyFromType(this.GetType());` is called from a static method, where `this` does not exist. 
`error` param should be assigned null when no errors occurred.

**Comment by RickStrahl** [comment]
Thanks - my bad. I adjusted the code to a self contained static class from an instance class I was actually using and in the process fat fingered the sample. I never went back to check it...

Anyway updated the example, should be fine now. Thank you.
