### ISSUE TITLE
Updated Nuget Package

### ISSUE THREAD

**Issue by fergie319** [RickStrahl/Westwind.RazorHosting#16]
Hi, I just started using this library and it is great!  I just ran into an issue with Layouts, though.  I inspected the dlls and it looks like the latest published nuget package is missing the Layout changes.  Can you update the nuget package with the latest?

**Comment by RickStrahl** [comment]
The layout changes should be in 3.1.

Note Layout only works with RazorFolderHostContainer().

**Comment by RickStrahl** [comment]
I've just updated the package to 3.2.
