### ISSUE TITLE
There is a error when processing a template with LF line separator.

### ISSUE THREAD

**Issue by mlershov** [RickStrahl/Westwind.RazorHosting#17]
Hello!
There is a error when processing a template with LF line separator (\n instead of \r\n ).

Method RazorEngine.FixupTemplate can be changed:

                int at = template.IndexOf("@model ");
                int at2 = template.IndexOf("\r\n", at);
                // Added by me
                if (at2 == -1)
                {
                    at2 = template.IndexOf("\n", at);
                }

**Comment by RickStrahl** [comment]
The easier fix here is probably to just look for `\n` - The  `.Trim()` in the model class parsing should remove the `\r`.

    int at = template.IndexOf("@model ");
    int at2 = template.IndexOf("\n", at);
    var line = template.Substring(at, at2 - at);
    var modelClass = line.Replace("@model ", "").Trim();
