### ISSUE TITLE
Support for newer C# language features, e.g. string interpolation

### ISSUE THREAD

**Issue by ManfredLange** [RickStrahl/Westwind.RazorHosting#23]
It's possible to user a newer C# compiler in a project by adding the appropriate nuget package. For example this adds string interpolation.

Rendering a template that uses newer C# language features fails with error messages such as 

"Line: 29, Column: 18, Error: Unexpected character '$'Line: 33, Column: 27, Error: Unexpected character '$'"

Is there a way to instruct Westwind.RazorHosting to use a particular C# compiler?

**Comment by ManfredLange** [comment]
Looks as if https://github.com/RickStrahl/Westwind.RazorHosting/blob/de9b5b06590a8950ac7993035c8f0986ca95b855/Westwind.RazorHosting/Core/RazorEngine.cs#L456

uses class `Microsoft.CSharp.CSharpCodeProvider` which appears to be different to `Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider`

It doesn't look as if installing nuget package `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` maps `new Microsoft.CSharp.CSharpCodeProvider()` to `new Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider()`.

Is there some configuration required in app.config or web.config to specify which CSharpCodeProvider Westwind.RazorHosting is using?

**Comment by RickStrahl** [comment]
Looking at this now. I don't know what needs to happen since ASP.NET MVC when run in a project handles this internally. Adding the package alone is not enough. 

I can't find any documentation on what needs to happen. app.config with CodeDom configuration sections might work, but I believe there's still a Razor specific switch that needs to be thrown.

Have to check in a MVC 5 project, but the problem is that some of these settings are defaulted.

**Comment by RickStrahl** [comment]
Ok... so I got this to work by replacing the provider but for some reason the platform is looking in the wrong place for the compiler.

Adding the package the compiler output creates:

`projectPath\Westwind.RazorHosting.Tests\bin\Debug\roslyn\csc.exe`

But the compiler is looking for the roslyn compiler in:

`projectPath\Westwind.RazorHosting.Tests\bin\Debug\bin\roslyn\csc.exe`

Not sure what that's all about.

IOW, if you manually copy the \roslyn\ folder into a `bin\roslyn` folder in the output folder the new language syntax works.

**Comment by ManfredLange** [comment]
Thank you, sounds good!

I grabbed the source code for Westwind.RazorHosting and changed it to use Roslyn. This allowed me to get over the hurdle with the C# 7 features. It now complains about certain classes not existing but that is related to our code using ASP.NET MVC 5 classe such as `HttpHelper` or `Url` in the template. I think these can be resolved by adding in the appropriate assemblies as references but we'll try that next.

One of the challenges with this approach is that we need to find a way of ensuring the `roslyn` folder with the C# compiler is available at the correct location. I'm confident there is some solution for this.

Some context: We are rendering partials into strings which are sent back as a response to an ajax call. While this would work fine if it was just a single partial, we want to be in a position to send back an array of such partials which are then handled by javascript. The specific issue popped up outside of the web project. We also have tests in a different project that test the controllers in isolation (with some mocking but no HttpContext etc).

**Comment by ManfredLange** [comment]
That leaves the question if it would be worth considering to allow passing a CSharpCodeProvider() to the RazorEngine in some form. By default it could still use the one from Microsoft.CSharp as it would perhaps avoid the dependency on the roslyn packages. I can see that `Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider` derives from `Microsoft.CSharp.CSharpCodeProvider` so that may be an opportunity. Perhaps this could be a parameter or property for the HostContainer classes?

**Comment by RickStrahl** [comment]
Ok got it to work:

* Add Microsoft.CodeDom.Providers.DotnetCompilerPlatform package to Westwind.RazorHosting
* Change the CSharpProvider() to use the new Provider
* Add the package to the target project as well (otherwise the Roslyn binaries won't install it looks like)
* Add the following to the app.config for the target project (wouldn't work without for me)

```xml
<system.codedom>
    <compilers>
      <compiler language="c#;cs;csharp" extension=".cs"
        type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        warningLevel="4" compilerOptions="/langversion:default /nowarn:1659;1699;1701"/>
      <compiler language="vb;vbs;visualbasic;vbscript" extension=".vb"
        type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        warningLevel="4" compilerOptions="/langversion:default /nowarn:41008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+"/>
    </compilers>
</system.codedom>
```

**Comment by ManfredLange** [comment]
Great! I'll sort out the missing symbols in our razor templates and then switch to your solution.

Thank you, Rick, for the fast response! Much appreciated.

**Comment by RickStrahl** [comment]
Maybe hold up a little. I'm adding a CSharpCodeProvider to RazorEngine and the host container to pass it through now.

**Comment by ManfredLange** [comment]
Class `RazorTemplateFolderHost<TModel>` doesn't have a property named `Url` of type `UrlHelper`.

Would you suggest to implement a new class derived from host container which in turn uses a new template base class derived from `RazorTemplateFolderHost<TModel>`?

**Comment by RickStrahl** [comment]
So you can now do this:

```csharp
var host = new RazorFolderHostContainer();
host.CodeProvider = new Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider();
```

or 

```csharp
// new behavior
var cs = new Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider()
var engine = new RazorEngine(cs);

// old behavior
var engine = new RazorEngine();
```

**Comment by ManfredLange** [comment]
Another challenge is the use of class `HtmlHelper` without namespace. There is a class `System.Web.Mvc.HtmlHelper, and there is also a class `Westwind.RazorHost.HtmlHelper`.

Perhaps the file with the generated C# code should not use `using Westwind.RazorHosting;` and instead use fully qualified names where it needs a class from that namespace?

**Comment by RickStrahl** [comment]
Start a new issue for those please.

**Comment by ManfredLange** [comment]
Did you already push the changes to Github?

**Comment by RickStrahl** [comment]
Pushed and documentation has been updated:

https://github.com/RickStrahl/Westwind.RazorHosting#using-latest-c-language-features

c29aedc9b93fcf21adc73fb39c50ab4ff1dbc054

**Comment by RickStrahl** [comment]
Thanks for your help on this issue - this has been on the backlog on a 'nice to have list' and I never quite figured this out until you pointed out that the new CSharpProvider inherits from the old so it was simply a matter of plugging the new one in. Thank you!
