### ISSUE TITLE
Using RazorHosting with in an AzureFunction

### ISSUE THREAD

**Issue by grahamehorner** [RickStrahl/Westwind.RazorHosting#26]
I'm seeing the following error when using the RazorHosting with in an C# AzureFunction v2 with the nightly build nuget feed

System.Private.CoreLib: Exception while executing function: SendNotification. Microsoft.Azure.WebJobs.Host: Could not load file or assembly 'System.CodeDom, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified

**Comment by RickStrahl** [comment]
I think these are permission issues that are simply not allowed in Azure functions. If CodeDom can't load this code will simply not work as it's required. Azure functions have a limited security profile can code compilation apparently is not part of it unless there are settings that allow it.
