### ISSUE TITLE
Unable to parse to html

### ISSUE THREAD

**Issue by smallisettyzc** [RickStrahl/Westwind.RazorHosting#7]
I am getting the following error while parsing to HTML

System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.InternalSubStringWithChecks(Int32 startIndex, Int32 length, Boolean fAlwaysCopy)
   at Westwind.RazorHosting.RazorEngine`1.FixupTemplate(String template)
   at Westwind.RazorHosting.RazorEngine`1.CompileTemplate(TextReader templateReader, String generatedNamespace, String generatedClassName)
   at Westwind.RazorHosting.RazorEngine`1.RenderTemplate(TextReader templateSourceReader, Object model, TextWriter outputWriter)

Is there any workaround for it?

**Comment by RickStrahl** [comment]
You'll need to provide more info. Most likely you have an expression error in the script your running.

**Comment by rmtew** [comment]
This is because the template text has `\n` rather than the `\r\n` for end of lines where `FixupTemplate` is coded to expect the latter.  While it'd be nice if this was fixed, or even raised an error with a message that indicated this was the problem, anyone else who is searching for the exception in this error will hopefully read this and can add some code like the following to work around it:

                string templateText = File.ReadAllText(templateFilePath);
                if (!templateText.Contains("\r\n"))
                {
                    templateText = templateText.Replace("\n", "\r\n");
                }

**Comment by kgiszewski** [comment]
@rmtew Is correct. Just ran into this. Happened when it worked locally, got sent to source control, but the line endings were modified.

Would be great to line endings in the config.

**Comment by RickStrahl** [comment]
Hmmm, I thought I fixed that in the last round of updates. Slightly different code though. The above is too volatile - that can break in all sorts of ways.

**Comment by kgiszewski** [comment]
Ok, well I thought I'd help. I will close the PR.
