### ISSUE TITLE
Throw on error

### ISSUE THREAD

**Issue by bernhard-hofmann** [RickStrahl/Westwind.RazorHosting#9]
The interface doesn't throw in the event of errors. The caller must know that errors will be available in `host.ErrorMessage`.

I'd like a feature that allows me to set a property such as `ThrowOnError` to `true` so that the call will throw if there is an error rendering the template.

**Comment by RickStrahl** [comment]
Added RazorHostContainer.ThrowExceptions to provide the ability to optionally capture exceptions. Custom RazorHostContainerException is used that captures the most relevant data as part of the exception.

e2db946d20a4d4b6a8357ebc400428f9434af553
